---
title: "Getting into looping - Zoë Keating"
author: "Sara Hänzi"
date: "2023-12-31"
categories: [listening, inspiration]
---

Playing in orchestras and ensembles has always been fun - but coming back to music a bit more after a more sporty phase, I wasn't quite attracted by classical ensembles. Then, with the help of some friends, I discovered looping, where you play and record yourself, so you can build up a whole ensemble on your own. I was fascinated, and this piece by [Zoë Keating](https://www.zoekeating.com/) finally convinced me that I needed to get a looper:

<iframe style="border: 0; width: 100%; height: 120px;" src="https://bandcamp.com/EmbeddedPlayer/album=3620198981/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/artwork=small/track=1063169438/transparent=true/" seamless><a href="https://music.zoekeating.com/album/one-cello-x-16-ep">One Cello x 16 (EP) by Zoe Keating</a></iframe>

If you are impatient, fast-forward to 2:10, I think it gets really fun from 2:20 or so. The cello is also very cool for looping because it is low enough to have a base, but flexible enough to play higher melodies and all sorts of different sounds. Another exmple where we can see Zoë play:

<iframe width="560" height="315" src="https://www.youtube.com/embed/jToYxrS0oKw?si=KZXnxHTmo_GZtMdn" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

While Zoë uses a laptop and a midi controller, and programs her sequences herself, I decided I didn't want to stare at a screen yet again, so I bought myself a pedal looper, and thereby started my looping adventure.

### Artists mentioned

Zoë Keating: [website](https://www.zoekeating.com/), her [albums on bandcamp](https://zoekeating.bandcamp.com/)