project:
  type: website

website:
  title: "Music"
  navbar:
    right:
      #- about.qmd
      - icon: github
        href: https://github.com/shaenzi
      - icon: mastodon
        href: https://mas.to/@sarahaenzi
      - text: Main Website
        href: https://www.sarahaenzi.com/
format:
  html:
    theme: solar
    css: styles.css



