---
title: "Tiny desk concerts"
author: "Sara Hänzi"
date: "2024-01-17"
categories: [listening, inspiration]
---

Not much is needed for an exceptional musical experience - a tiny desk behind which musicians can play and an audience is all that is required with NPR's Tiny Desk concert series. 
Luckily for us, we can watch online even if we do not make it to the studio. While I haven't listened to nearly enough of them, I already have quite a few favouriters, which I'd like to share with you:

## Goat Rodeo

The Goat Rodeo Sessions is an album by/with Edgar Meyer, Chris Thile, Stuart Duncan, and Yo-Yo Ma. Classically inclined people will recognise at least Ma's name, and yes, some classically-trained virtuosity is an aspect that can be heard, but there is so much more:

<iframe width="560" height="315" src="https://www.youtube.com/embed/O7EcT5YzKhQ?si=gw82MORxIoQH0xEW" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

## Gaelynn Lea

As a violin player myself, I know many of the sounds that a violin can create. I learnt a whole lot of new ones with this video, though. Gaelynn Lea's playing won the Tiny Desk contest of that year, and it really is something special:

<iframe width="560" height="315" src="https://www.youtube.com/embed/n6oSeODGmoQ?si=uYgoD_58nBnyMsYU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

## Imogen Heap and fancy technology

I'm starting to learn about all the fun stuff you can do with music when it is digital. Nevertheless, having something physical in your hands still has an appeasl - Imogen Heap combines both with super-fancy gloves, which allow her to control digital effects with gestures:

<iframe width="560" height="315" src="https://www.youtube.com/embed/3QtklTXbKUQ?si=YH1fqjdaXKmI0AIe" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

Is that enough inspiration for today?

### Artists mentioned

- [Edgar Meyer](https://en.wikipedia.org/wiki/Edgar_Meyer)
- [Chris Thile](https://www.christhile.com/)
- [Stuart Duncan](https://en.wikipedia.org/wiki/Stuart_Duncan)
- [Yo-Yo Ma](https://www.yo-yoma.com/)
- [Gaelynn Lea](https://violinscratches.com/)
- [Imogen Heap](https://imogenheap.app/)